server:
  port: 8080
info:
  hello:
    "I am a service"
management:
  security:
    enabled: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://35.198.254.195:3306/account
    username: user01
    password: password
    initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy